/**
 * Listening bank — 40 original practice items (source: original
 * practice, written for this app; no official past papers). Each
 * transcript is played ONCE (text-to-speech) to train the one-listen
 * rule. Traps mirror real exam distractor logic.
 */
export interface ListeningItem {
  id: string;
  kind: "annonce" | "dialogue" | "radio" | "micro-trottoir" | "message";
  transcript: string;
  question: string;
  options: string[];
  answer: number; // index
  trap: string;
  level: 1 | 2 | 3;
  source: "original practice";
}

const s = "original practice" as const;

export const LISTENING_ITEMS: ListeningItem[] = [
  {
    id: "co-01", kind: "annonce", level: 1, source: s,
    transcript: "Votre attention s'il vous plaît. Le train à destination de Québec, départ prévu à quinze heures dix, partira finalement de la voie sept, et non de la voie deux. Nous vous prions de nous excuser pour ce changement.",
    question: "Que doivent faire les voyageurs pour Québec ?",
    options: ["Attendre un nouveau train à 17 h", "Aller à la voie 7", "Rester à la voie 2", "Changer de gare"],
    answer: 1,
    trap: "« quinze heures dix » et « voie deux » sont prononcés : l'examen compte sur la confusion des nombres entendus.",
  },
  {
    id: "co-02", kind: "message", level: 1, source: s,
    transcript: "Bonjour, c'est le cabinet du docteur Lemoine. Votre rendez-vous de jeudi quatorze heures est annulé, le docteur est absent. Nous pouvons vous proposer vendredi à neuf heures trente ou lundi à seize heures. Rappelez-nous pour confirmer.",
    question: "Pourquoi le cabinet appelle-t-il ?",
    options: ["Pour confirmer le rendez-vous de jeudi", "Pour annuler et proposer d'autres horaires", "Pour demander un paiement", "Pour annoncer un retard du docteur"],
    answer: 1,
    trap: "« jeudi quatorze heures » est répété — mais la fonction du message est l'annulation, pas la confirmation.",
  },
  {
    id: "co-03", kind: "dialogue", level: 1, source: s,
    transcript: "— Bonjour, je cherche un appartement à louer, deux chambres, près du métro. — Nous avons un trois-pièces à Villeray, huit cent cinquante dollars par mois, chauffage inclus. — Et les animaux sont acceptés ? — Malheureusement non, le propriétaire refuse.",
    question: "Quel est le problème pour le client ?",
    options: ["Le loyer est trop cher", "Le chauffage n'est pas inclus", "Les animaux ne sont pas acceptés", "L'appartement est loin du métro"],
    answer: 2,
    trap: "Le prix et le chauffage sont mentionnés positivement ; seule la dernière réplique porte le refus.",
  },
  {
    id: "co-04", kind: "radio", level: 2, source: s,
    transcript: "Selon une étude publiée ce matin, près d'un tiers des travailleurs canadiens souhaitent continuer le télétravail à temps plein. Cependant, la majorité des employeurs préfèrent un modèle hybride, deux à trois jours au bureau par semaine.",
    question: "Que préfèrent la plupart des employeurs ?",
    options: ["Le télétravail à temps plein", "Le retour complet au bureau", "Un modèle hybride", "La semaine de quatre jours"],
    answer: 2,
    trap: "« un tiers des travailleurs » concerne les employés, pas les employeurs — attention à qui veut quoi.",
  },
  {
    id: "co-05", kind: "micro-trottoir", level: 2, source: s,
    transcript: "Moi, franchement, les transports en commun, j'aimerais bien les prendre, mais avec deux enfants à déposer à deux écoles différentes, c'est mission impossible. Alors oui, je prends la voiture, même si ça coûte cher.",
    question: "Pourquoi cette personne prend-elle la voiture ?",
    options: ["Parce que c'est moins cher", "Parce qu'elle déteste le bus", "Par obligation d'organisation familiale", "Parce qu'elle habite loin"],
    answer: 2,
    trap: "Elle dit « j'aimerais bien les prendre » : l'option « elle déteste le bus » contredit l'intention exprimée.",
  },
  {
    id: "co-06", kind: "annonce", level: 1, source: s,
    transcript: "Chers clients, notre magasin fermera exceptionnellement à dix-huit heures aujourd'hui au lieu de vingt et une heures, en raison d'un inventaire. Merci de vous diriger vers les caisses.",
    question: "Pourquoi le magasin ferme-t-il plus tôt ?",
    options: ["À cause d'une panne", "Pour un inventaire", "Pour des travaux", "À cause d'un jour férié"],
    answer: 1,
    trap: "Deux horaires sont donnés ; la raison (« inventaire ») n'est dite qu'une fois, en fin de phrase.",
  },
  {
    id: "co-07", kind: "dialogue", level: 2, source: s,
    transcript: "— Alors, cette entrevue d'embauche ? — Le poste est intéressant et l'équipe sympathique. Par contre, le salaire est plus bas que ce que je gagne actuellement. Je vais quand même réfléchir, à cause des horaires flexibles.",
    question: "Quel est le point négatif du poste ?",
    options: ["L'équipe", "Les horaires", "Le salaire", "Les tâches"],
    answer: 2,
    trap: "« par contre » signale le contraste : tout ce qui précède est positif, ce qui suit est le vrai négatif.",
  },
  {
    id: "co-08", kind: "message", level: 1, source: s,
    transcript: "Salut, c'est Karim. Pour samedi, petit changement : on ne se retrouve plus au restaurant à midi, mais chez Léa à treize heures. Apporte quelque chose à boire. Confirme-moi par texto, s'il te plaît.",
    question: "Qu'est-ce qui change pour samedi ?",
    options: ["Le jour de la rencontre", "Le lieu et l'heure", "Les personnes invitées", "Rien, c'est confirmé"],
    answer: 1,
    trap: "Le jour reste samedi ; ce sont le lieu (chez Léa) et l'heure (13 h) qui changent.",
  },
  {
    id: "co-09", kind: "radio", level: 3, source: s,
    transcript: "La ville annonce la gratuité des bus pour les moins de dix-huit ans dès septembre. Une mesure saluée par les associations de parents, mais critiquée par l'opposition, qui rappelle que le réseau, déjà saturé, aurait d'abord besoin d'investissements.",
    question: "Que reproche l'opposition à cette mesure ?",
    options: ["Elle coûte trop cher aux familles", "Elle arrive trop tard", "Elle ignore la saturation du réseau", "Elle exclut les étudiants"],
    answer: 2,
    trap: "« saluée par les associations » peut faire choisir une option positive ; la critique vient après « mais ».",
  },
  {
    id: "co-10", kind: "dialogue", level: 2, source: s,
    transcript: "— Bonjour, j'ai reçu une facture d'électricité de trois cent vingt dollars, c'est le double d'habitude ! — Je vérifie… En effet, votre compteur a été estimé, pas relevé. Envoyez-nous une photo du compteur et nous corrigerons la facture.",
    question: "Que doit faire le client ?",
    options: ["Payer immédiatement la facture", "Changer de fournisseur", "Envoyer une photo du compteur", "Prendre rendez-vous avec un technicien"],
    answer: 2,
    trap: "Le montant « trois cent vingt » attire l'attention, mais la question porte sur l'action demandée.",
  },
  {
    id: "co-11", kind: "annonce", level: 2, source: s,
    transcript: "En raison de travaux, la ligne orange du métro est interrompue entre les stations Jarry et Beaubien ce week-end. Des navettes gratuites assurent la liaison toutes les dix minutes. Reprise normale du service lundi à cinq heures trente.",
    question: "Comment circuler entre Jarry et Beaubien ce week-end ?",
    options: ["En métro, service normal", "En navette gratuite", "En taxi remboursé", "Ce n'est pas possible"],
    answer: 1,
    trap: "« Reprise normale lundi » ne signifie pas qu'aucune solution n'existe avant : les navettes sont la réponse.",
  },
  {
    id: "co-12", kind: "micro-trottoir", level: 2, source: s,
    transcript: "Les cours en ligne ? Au début, j'étais contre, je trouvais ça froid. Finalement, j'ai changé d'avis : je gagne deux heures de transport par jour, et les enregistrements me permettent de revoir ce que je n'ai pas compris.",
    question: "Quelle est l'opinion actuelle de cette personne sur les cours en ligne ?",
    options: ["Elle y est toujours opposée", "Elle est devenue favorable", "Elle n'a pas d'avis", "Elle les trouve froids"],
    answer: 1,
    trap: "« j'étais contre » décrit le passé ; « finalement, j'ai changé d'avis » donne la position actuelle.",
  },
  {
    id: "co-13", kind: "message", level: 2, source: s,
    transcript: "Bonjour, ici la bibliothèque municipale. Le livre que vous avez réservé est disponible. Attention : nous le gardons sept jours seulement, jusqu'au vendredi vingt-deux. Passé ce délai, il retournera en rayon.",
    question: "Que se passe-t-il après le vendredi 22 ?",
    options: ["Le livre sera prêté à quelqu'un d'autre automatiquement", "La réservation sera annulée", "Une amende sera facturée", "Le livre sera envoyé par la poste"],
    answer: 1,
    trap: "« retournera en rayon » = fin de la réservation ; aucune amende n'est mentionnée.",
  },
  {
    id: "co-14", kind: "radio", level: 3, source: s,
    transcript: "Le prix moyen des loyers a encore augmenté de six pour cent cette année. Paradoxalement, le nombre de logements vacants progresse aussi : beaucoup restent vides parce qu'ils sont trop chers, précisément, pour les revenus des ménages de la région.",
    question: "Pourquoi certains logements restent-ils vides ?",
    options: ["Ils sont en mauvais état", "Ils sont trop éloignés des villes", "Leurs loyers dépassent les moyens des habitants", "Les propriétaires refusent de louer"],
    answer: 2,
    trap: "« paradoxalement » annonce une explication surprenante : le lien prix/vacance est la clé, pas l'état des logements.",
  },
  {
    id: "co-15", kind: "dialogue", level: 1, source: s,
    transcript: "— Excusez-moi, la pharmacie est encore ouverte ? — Elle ferme à vingt heures, il vous reste un quart d'heure. — Parfait, c'est pour retirer une ordonnance. — Alors dépêchez-vous, le comptoir des ordonnances ferme dix minutes avant.",
    question: "À quelle heure ferme le comptoir des ordonnances ?",
    options: ["19 h 45", "19 h 50", "20 h 00", "20 h 10"],
    answer: 1,
    trap: "Il faut calculer : 20 h moins dix minutes = 19 h 50. « un quart d'heure » sert de distracteur.",
  },
  {
    id: "co-16", kind: "annonce", level: 1, source: s,
    transcript: "Mesdames et messieurs, en raison des vents violents, l'embarquement du vol AC-482 pour Halifax est retardé d'environ quarante-cinq minutes. Restez à proximité de la porte douze, l'embarquement pourrait commencer plus tôt que prévu.",
    question: "Que demande-t-on aux passagers ?",
    options: ["De changer de porte", "De rester près de la porte 12", "De récupérer leurs bagages", "De réserver un autre vol"],
    answer: 1,
    trap: "Le retard de « quarante-cinq minutes » attire l'oreille ; la consigne est de rester à proximité.",
  },
  {
    id: "co-17", kind: "dialogue", level: 2, source: s,
    transcript: "— Tu as vu l'annonce pour le cours de natation ? — Oui, mais c'est complet pour les débutants. Il reste des places le mardi soir, niveau intermédiaire. — Mardi, je finis à dix-huit heures… ça commence à quelle heure ? — Dix-neuf heures quinze, tu as le temps.",
    question: "Quelle est la situation du cours pour débutants ?",
    options: ["Il est complet", "Il a lieu le mardi soir", "Il commence à 19 h 15", "Il est annulé"],
    answer: 0,
    trap: "Les horaires du mardi concernent le niveau intermédiaire, pas le cours débutants.",
  },
  {
    id: "co-18", kind: "micro-trottoir", level: 3, source: s,
    transcript: "L'interdiction des téléphones à l'école ? Sur le principe, je comprends. Mais soyons honnêtes : le problème, ce n'est pas l'objet, c'est l'usage. Interdire sans éduquer, ça déplace le problème à la sortie des classes, voilà tout.",
    question: "Que pense cette personne de l'interdiction ?",
    options: ["Elle est totalement pour", "Elle est totalement contre", "Elle la juge insuffisante sans éducation", "Elle n'a pas compris la mesure"],
    answer: 2,
    trap: "« Sur le principe, je comprends » n'est pas une adhésion complète ; le « mais » porte le vrai message.",
  },
  {
    id: "co-19", kind: "message", level: 1, source: s,
    transcript: "Bonjour, c'est le garage Duval. Votre voiture est prête. Le remplacement des freins a coûté deux cent quatre-vingts dollars, un peu moins que le devis. Nous sommes ouverts jusqu'à dix-sept heures trente aujourd'hui.",
    question: "Que dit le garagiste à propos du prix ?",
    options: ["Il est plus élevé que prévu", "Il est inférieur au devis", "Il doit encore être calculé", "Il sera payé par l'assurance"],
    answer: 1,
    trap: "Le montant exact importe moins que la comparaison « un peu moins que le devis ».",
  },
  {
    id: "co-20", kind: "radio", level: 2, source: s,
    transcript: "Bonne nouvelle pour les cyclistes : la ville double la longueur des pistes protégées d'ici deux ans. Les commerçants du centre, eux, s'inquiètent de la disparition d'une centaine de places de stationnement.",
    question: "Qui exprime une inquiétude ?",
    options: ["Les cyclistes", "Les commerçants du centre", "La mairie", "Les automobilistes de banlieue"],
    answer: 1,
    trap: "L'annonce commence par « bonne nouvelle » — le point de vue inquiet arrive dans la deuxième phrase.",
  },
  {
    id: "co-21", kind: "dialogue", level: 2, source: s,
    transcript: "— Bonjour, je voudrais ouvrir un compte bancaire. Je viens d'arriver au Canada. — Bienvenue ! Il nous faut deux pièces d'identité et une preuve d'adresse. — J'ai mon passeport et mon permis de conduire, mais pas encore de preuve d'adresse. — Dans ce cas, revenez avec un bail ou une facture à votre nom.",
    question: "Pourquoi le client doit-il revenir ?",
    options: ["Il n'a pas de passeport", "Il lui manque une preuve d'adresse", "La banque est fermée", "Il doit prendre rendez-vous"],
    answer: 1,
    trap: "Deux documents sur trois sont acceptés ; c'est le document manquant qui bloque l'ouverture.",
  },
  {
    id: "co-22", kind: "annonce", level: 2, source: s,
    transcript: "Le service des impôts vous informe : la date limite de déclaration est le trente avril. Les personnes travaillant à leur compte bénéficient d'un délai jusqu'au quinze juin, mais attention : tout solde dû doit être payé dès le trente avril.",
    question: "Que doivent faire les travailleurs autonomes avant le 30 avril ?",
    options: ["Envoyer leur déclaration", "Payer le solde dû", "Prendre rendez-vous", "Rien, ils ont jusqu'au 15 juin"],
    answer: 1,
    trap: "Deux dates coexistent : le délai du 15 juin concerne la déclaration, pas le paiement.",
  },
  {
    id: "co-23", kind: "micro-trottoir", level: 2, source: s,
    transcript: "Cuisiner tous les soirs ? Impossible avec mes horaires. Alors le dimanche, je prépare trois ou quatre plats pour la semaine. Ce n'est pas de la grande cuisine, mais au moins on évite les livraisons à trente dollars.",
    question: "Quelle solution cette personne a-t-elle trouvée ?",
    options: ["Commander des livraisons", "Cuisiner chaque soir rapidement", "Préparer les repas à l'avance le dimanche", "Manger au restaurant"],
    answer: 2,
    trap: "Les livraisons sont mentionnées comme ce qu'elle évite, pas comme sa solution.",
  },
  {
    id: "co-24", kind: "radio", level: 3, source: s,
    transcript: "Faut-il allonger l'année scolaire ? Les partisans avancent que les longues vacances creusent les écarts entre élèves. Leurs opposants répondent que le problème n'est pas la durée des vacances, mais l'inégalité d'accès aux activités pendant celles-ci.",
    question: "Selon les opposants, quel est le vrai problème ?",
    options: ["La durée des vacances", "Le niveau des enseignants", "L'inégalité d'accès aux activités estivales", "Le coût de l'école"],
    answer: 2,
    trap: "Les deux camps parlent des vacances : il faut attribuer chaque argument au bon camp.",
  },
  {
    id: "co-25", kind: "dialogue", level: 1, source: s,
    transcript: "— Allô, je vous appelle pour l'annonce du vélo à vendre. Il est toujours disponible ? — Oui. Il a deux ans, très peu servi. Je demande cent vingt dollars. — Est-ce que quatre-vingt-dix vous irait ? — Disons cent, et je vous ajoute l'antivol.",
    question: "Sur quel prix les deux personnes s'entendent-elles ?",
    options: ["90 dollars", "100 dollars", "110 dollars", "120 dollars"],
    answer: 1,
    trap: "Trois prix sont prononcés ; la contre-proposition finale « disons cent » emporte l'accord.",
  },
  {
    id: "co-26", kind: "message", level: 2, source: s,
    transcript: "Bonjour, c'est madame Tremblay, la directrice de l'école. Votre fils va bien, rassurez-vous. Je vous appelle car il a oublié son inhalateur à la maison, d'après ce qu'il nous dit. Pouvez-vous le déposer au secrétariat avant la récréation de quatorze heures ?",
    question: "Pourquoi la directrice appelle-t-elle ?",
    options: ["L'enfant est malade", "L'enfant a eu un accident", "Il faut apporter un médicament oublié", "L'enfant a été absent"],
    answer: 2,
    trap: "« Votre fils va bien, rassurez-vous » élimine d'emblée les options alarmantes.",
  },
  {
    id: "co-27", kind: "annonce", level: 1, source: s,
    transcript: "La piscine municipale sera fermée du trois au dix mars pour l'entretien annuel des bassins. Les abonnements seront automatiquement prolongés d'une semaine. Aucune démarche n'est nécessaire.",
    question: "Que doivent faire les abonnés ?",
    options: ["Demander un remboursement", "Renouveler leur abonnement", "Rien du tout", "S'inscrire sur une liste"],
    answer: 2,
    trap: "« automatiquement » et « aucune démarche » : l'examen vérifie si vous entendez la négation.",
  },
  {
    id: "co-28", kind: "dialogue", level: 3, source: s,
    transcript: "— Vous avez demandé un temps partiel, c'est bien ça ? — Oui, quatre jours par semaine. — Votre dossier est solide, mais le service est en sous-effectif jusqu'en janvier. Je vous propose de commencer le temps partiel à ce moment-là, avec un vendredi sur deux libéré d'ici là.",
    question: "Que propose le responsable ?",
    options: ["Un refus définitif du temps partiel", "Le temps partiel immédiat", "Un compromis transitoire jusqu'en janvier", "Une augmentation de salaire"],
    answer: 2,
    trap: "Ni refus ni accord immédiat : la proposition est intermédiaire, typique des dialogues professionnels.",
  },
  {
    id: "co-29", kind: "micro-trottoir", level: 2, source: s,
    transcript: "Moi, apprendre le français, je le fais surtout le matin, avant le travail. Le soir, honnêtement, mon cerveau ne suit plus. Vingt minutes au réveil, un café, une leçon — c'est devenu automatique, comme me brosser les dents.",
    question: "Pourquoi cette personne étudie-t-elle le matin ?",
    options: ["Elle travaille la nuit", "Elle est trop fatiguée le soir", "Son cours n'existe que le matin", "Elle veut éviter sa famille"],
    answer: 1,
    trap: "« mon cerveau ne suit plus » est une image : il faut la relier à la fatigue du soir.",
  },
  {
    id: "co-30", kind: "radio", level: 2, source: s,
    transcript: "Météo : un avertissement de chaleur est en vigueur jusqu'à jeudi soir. On attend trente-quatre degrés demain. Rappel des consignes : buvez de l'eau régulièrement, évitez les efforts entre midi et seize heures, et prenez des nouvelles des personnes âgées de votre entourage.",
    question: "Quelle consigne est donnée pour la mi-journée ?",
    options: ["Rester à l'intérieur toute la journée", "Éviter les efforts entre 12 h et 16 h", "Ne pas boire trop d'eau", "Fermer les fenêtres"],
    answer: 1,
    trap: "Trois consignes sont énumérées ; la question ne porte que sur celle liée à la mi-journée.",
  },
  {
    id: "co-31", kind: "dialogue", level: 2, source: s,
    transcript: "— Ce forfait mobile à vingt-cinq dollars, il inclut quoi exactement ? — Appels et textos illimités au Canada, et dix gigas de données. — Et vers l'étranger ? — C'est en supplément, sauf si vous prenez l'option internationale à dix dollars de plus.",
    question: "Que faut-il faire pour appeler l'étranger sans supplément à l'usage ?",
    options: ["Rien, c'est inclus dans le forfait de base", "Prendre l'option internationale", "Changer d'opérateur", "Utiliser uniquement les textos"],
    answer: 1,
    trap: "« illimités » concerne le Canada seulement ; la restriction arrive dans la deuxième réplique.",
  },
  {
    id: "co-32", kind: "annonce", level: 3, source: s,
    transcript: "Suite à un mouvement de grève, les collectes de déchets sont reportées de quarante-huit heures dans tous les quartiers. Les collectes de recyclage, assurées par un autre prestataire, ont lieu normalement. Merci de rentrer vos bacs non collectés.",
    question: "Qu'en est-il du recyclage ?",
    options: ["Reporté de 48 heures aussi", "Annulé cette semaine", "Maintenu normalement", "Regroupé avec les déchets"],
    answer: 2,
    trap: "Deux services, deux régimes : l'examen teste si vous distinguez « déchets » et « recyclage ».",
  },
  {
    id: "co-33", kind: "message", level: 2, source: s,
    transcript: "Bonjour, service des admissions de l'université. Il manque une pièce à votre dossier : la traduction certifiée de votre diplôme. Vous pouvez la téléverser dans votre espace en ligne jusqu'au premier mai. Sans ce document, la candidature ne pourra pas être évaluée.",
    question: "Que se passe-t-il sans la traduction certifiée ?",
    options: ["Le dossier sera étudié avec retard", "La candidature ne sera pas évaluée", "Des frais supplémentaires s'appliquent", "Un entretien sera exigé"],
    answer: 1,
    trap: "« jusqu'au premier mai » peut évoquer un simple délai ; la conséquence est bien l'absence d'évaluation.",
  },
  {
    id: "co-34", kind: "micro-trottoir", level: 3, source: s,
    transcript: "Le compostage obligatoire ? Chez nous, ça se passe bien, contrairement à ce qu'on annonçait. Le plus dur, ce n'était pas l'odeur ni les mouches, c'était de changer les habitudes des trois premières semaines. Après, ça roule tout seul.",
    question: "Quelle a été la vraie difficulté selon cette personne ?",
    options: ["Les odeurs", "Les insectes", "Le changement d'habitudes au début", "Le coût du matériel"],
    answer: 2,
    trap: "Les odeurs et les mouches sont citées pour être écartées (« ce n'était pas… ») — piège classique.",
  },
  {
    id: "co-35", kind: "radio", level: 3, source: s,
    transcript: "L'organisme de défense des locataires rappelle qu'une hausse de loyer doit être notifiée par écrit et que le locataire peut la refuser sans quitter le logement. Dans ce cas, c'est au propriétaire de saisir le tribunal administratif s'il veut maintenir la hausse.",
    question: "Que peut faire un locataire qui refuse une hausse ?",
    options: ["Il doit quitter le logement", "Il doit saisir lui-même le tribunal", "Il peut rester ; c'est au propriétaire d'agir", "Il doit payer la hausse en attendant"],
    answer: 2,
    trap: "La charge de la démarche revient au propriétaire — l'inversion des rôles est le piège.",
  },
  {
    id: "co-36", kind: "dialogue", level: 1, source: s,
    transcript: "— Deux billets pour la séance de vingt heures, s'il vous plaît. — Il ne reste que le premier rang. Pour la séance de vingt-deux heures quinze, j'ai encore de bonnes places au centre. — Bon, va pour la séance plus tardive alors.",
    question: "Quelle séance les clients choisissent-ils finalement ?",
    options: ["20 h, premier rang", "20 h, au centre", "22 h 15", "Aucune, ils renoncent"],
    answer: 2,
    trap: "« va pour la séance plus tardive » exige de relier « plus tardive » à 22 h 15.",
  },
  {
    id: "co-37", kind: "annonce", level: 2, source: s,
    transcript: "Rappel du service de santé publique : la clinique de vaccination sans rendez-vous du samedi est déplacée au centre communautaire, six cent quatre-vingts rue Sainte-Catherine. L'ancienne adresse, rue Berri, n'accueille plus de patients.",
    question: "Où se rendre pour la vaccination du samedi ?",
    options: ["Rue Berri", "Rue Sainte-Catherine", "À l'hôpital", "En pharmacie uniquement"],
    answer: 1,
    trap: "Deux adresses sont prononcées ; l'ancienne est répétée en dernier, position piège classique.",
  },
  {
    id: "co-38", kind: "dialogue", level: 3, source: s,
    transcript: "— J'hésite entre le TEF et le TCF pour mon dossier. — Les deux sont acceptés. Moi, j'ai pris celui qui avait des dates plus tôt dans ma ville. Le contenu se prépare pareil : c'est le format des épreuves qui change un peu. — Donc pas de test « plus facile » ? — Exactement, c'est un mythe.",
    question: "Quel critère de choix cette personne recommande-t-elle ?",
    options: ["Choisir le test le plus facile", "Choisir selon les dates disponibles", "Choisir le moins cher", "Choisir selon la longueur des épreuves"],
    answer: 1,
    trap: "La question du « test plus facile » est posée puis explicitement démentie : « c'est un mythe ».",
  },
  {
    id: "co-39", kind: "micro-trottoir", level: 1, source: s,
    transcript: "Le marché du samedi matin, c'est mon rituel. Pas tellement pour les prix, qui se valent avec le supermarché, mais pour discuter avec les producteurs et choisir des produits de la région.",
    question: "Pourquoi cette personne va-t-elle au marché ?",
    options: ["Pour payer moins cher", "Pour le contact et les produits locaux", "Parce que c'est plus rapide", "Parce que le supermarché est fermé"],
    answer: 1,
    trap: "« Pas tellement pour les prix » neutralise l'option économique avant de donner la vraie raison.",
  },
  {
    id: "co-40", kind: "radio", level: 2, source: s,
    transcript: "Dernière minute : en raison d'une panne informatique, les demandes de permis de conduire ne peuvent être traitées ni au comptoir ni en ligne aujourd'hui. Les rendez-vous d'examen pratique sont toutefois maintenus. Un point sera fait à quinze heures.",
    question: "Qu'est-ce qui est maintenu aujourd'hui ?",
    options: ["Les demandes au comptoir", "Les demandes en ligne", "Les examens pratiques", "Rien du tout"],
    answer: 2,
    trap: "« ni… ni… » supprime deux services ; « toutefois » réintroduit celui qui reste — écoutez les négations.",
  },
];
