/**
 * Reading bank — 40 original practice items (source: original
 * practice). Trains the exam method: read the question first, scan,
 * identify paragraph function (example, contrast, cause), eliminate.
 * Heavy on admin French: housing, work, health, studies.
 */
export interface ReadingItem {
  id: string;
  topic: "logement" | "travail" | "santé" | "études" | "vie pratique" | "société";
  passage: string;
  question: string;
  options: string[];
  answer: number;
  explanation: string;
  level: 1 | 2 | 3;
  source: "original practice";
}

const s = "original practice" as const;

export const READING_ITEMS: ReadingItem[] = [
  {
    id: "ce-01", topic: "logement", level: 1, source: s,
    passage: "AVIS AUX RÉSIDENTS — L'eau chaude sera coupée mardi de 9 h à 15 h pour l'entretien du système de chauffage. L'eau froide restera disponible. Merci de votre compréhension. — La gérance",
    question: "Que se passe-t-il mardi ?",
    options: ["Toute l'eau est coupée", "Seule l'eau chaude est coupée", "Le chauffage est coupé toute la journée", "L'immeuble est fermé"],
    answer: 1,
    explanation: "« L'eau froide restera disponible » limite la coupure à l'eau chaude. Les avis d'immeuble précisent toujours la portée exacte.",
  },
  {
    id: "ce-02", topic: "travail", level: 1, source: s,
    passage: "Offre d'emploi — Commis d'entrepôt, temps plein, quart de soir (16 h – minuit). Salaire : 21 $/h, prime de soir incluse. Exigences : capacité à soulever 20 kg, français fonctionnel. Aucune expérience requise, formation offerte.",
    question: "Qui peut postuler à cette offre ?",
    options: ["Seulement les candidats expérimentés", "Les candidats disponibles le matin", "Les débutants acceptant le travail de soir", "Les candidats bilingues uniquement"],
    answer: 2,
    explanation: "« Aucune expérience requise » + horaire 16 h–minuit : il faut croiser deux informations de l'annonce.",
  },
  {
    id: "ce-03", topic: "santé", level: 2, source: s,
    passage: "Votre demande de carte d'assurance maladie a été reçue. Délai de traitement actuel : six semaines. Pendant cette période, conservez vos reçus de consultation : certains frais pourront vous être remboursés après l'émission de la carte.",
    question: "Que faut-il faire en attendant la carte ?",
    options: ["Reporter tout rendez-vous médical", "Payer et garder les reçus", "Téléphoner chaque semaine", "Refaire une demande"],
    answer: 1,
    explanation: "Le texte lie la conservation des reçus à un remboursement possible : c'est l'action demandée au lecteur.",
  },
  {
    id: "ce-04", topic: "études", level: 2, source: s,
    passage: "Les étudiants étrangers doivent s'inscrire à au moins douze crédits par session pour conserver leur statut à temps plein. Une seule exception : la dernière session avant la diplomation, où une inscription à temps partiel est tolérée si les crédits restants sont insuffisants.",
    question: "Quand un étudiant étranger peut-il étudier à temps partiel ?",
    options: ["Jamais", "À sa dernière session, sous condition", "Dès la deuxième année", "Sur simple demande écrite"],
    answer: 1,
    explanation: "« Une seule exception » annonce la réponse ; la condition (« crédits restants insuffisants ») fait partie de la bonne option.",
  },
  {
    id: "ce-05", topic: "logement", level: 2, source: s,
    passage: "Le bail se renouvelle automatiquement chaque année. Si vous ne souhaitez pas le renouveler, un avis écrit doit parvenir au propriétaire au moins trois mois avant l'échéance. Un courriel avec accusé de réception est accepté.",
    question: "Comment éviter le renouvellement du bail ?",
    options: ["Ne rien faire, il expire seul", "Téléphoner au propriétaire", "Envoyer un avis écrit trois mois avant", "Déménager sans prévenir"],
    answer: 2,
    explanation: "« automatiquement » signifie que le silence renouvelle le bail : seule la démarche écrite l'empêche.",
  },
  {
    id: "ce-06", topic: "société", level: 3, source: s,
    passage: "On présente souvent le télétravail comme un progrès social. Pourtant, les enquêtes récentes nuancent ce portrait : les salariés à distance sont promus moins souvent que leurs collègues présents au bureau, à performance égale. La flexibilité aurait donc un coût invisible.",
    question: "Quelle est la fonction de la deuxième phrase ?",
    options: ["Donner un exemple", "Apporter un contraste avec l'idée reçue", "Expliquer une cause", "Conclure le texte"],
    answer: 1,
    explanation: "« Pourtant » est un connecteur de contraste : la phrase s'oppose à l'idée présentée avant. Repérer la fonction des paragraphes est une compétence notée.",
  },
  {
    id: "ce-07", topic: "vie pratique", level: 1, source: s,
    passage: "RAPPEL — Le stationnement est interdit du côté pair de la rue les jours de déneigement, signalés par un feu orange clignotant. Les véhicules en infraction seront remorqués aux frais du propriétaire.",
    question: "Quand faut-il éviter le côté pair ?",
    options: ["Tous les jours d'hiver", "Quand le feu orange clignote", "Le week-end", "Quand il pleut"],
    answer: 1,
    explanation: "L'interdiction est conditionnelle : elle dépend du signal (feu clignotant), pas de la saison entière.",
  },
  {
    id: "ce-08", topic: "travail", level: 2, source: s,
    passage: "Madame, Monsieur, — Nous accusons réception de votre candidature au poste de réceptionniste. Votre profil a retenu notre attention ; toutefois, le poste exige une disponibilité les fins de semaine, ce que votre lettre ne précise pas. Merci de nous confirmer ce point avant le 12 mars.",
    question: "Que demande l'employeur au candidat ?",
    options: ["De refaire sa lettre entière", "De confirmer sa disponibilité de fin de semaine", "De passer une entrevue le 12 mars", "De fournir des références"],
    answer: 1,
    explanation: "« toutefois » introduit le point bloquant ; la demande précise suit immédiatement.",
  },
  {
    id: "ce-09", topic: "santé", level: 1, source: s,
    passage: "Notice — Prendre un comprimé matin et soir, au moment des repas. Ne pas dépasser deux comprimés par jour. En cas d'oubli, ne doublez pas la dose suivante. Consultez un médecin si les symptômes persistent au-delà de cinq jours.",
    question: "Que faire si l'on oublie une prise ?",
    options: ["Prendre deux comprimés à la prise suivante", "Continuer normalement sans doubler", "Arrêter le traitement", "Consulter immédiatement"],
    answer: 1,
    explanation: "« ne doublez pas la dose suivante » répond mot à mot ; la mention des cinq jours concerne un autre cas.",
  },
  {
    id: "ce-10", topic: "études", level: 1, source: s,
    passage: "Bibliothèque universitaire — Horaires de session d'examens : ouverture prolongée jusqu'à 23 h du lundi au vendredi. Les salles de travail en groupe se réservent en ligne, maximum trois heures par équipe et par jour.",
    question: "Combien de temps une équipe peut-elle réserver une salle chaque jour ?",
    options: ["Une heure", "Deux heures", "Trois heures", "Sans limite"],
    answer: 2,
    explanation: "Lecture de repérage : la question d'abord, puis balayage jusqu'à « maximum trois heures ».",
  },
  {
    id: "ce-11", topic: "logement", level: 3, source: s,
    passage: "Contrairement à une croyance répandue, le propriétaire ne peut pas refuser un locataire au motif qu'il a des enfants. En revanche, il peut légalement exiger une enquête de crédit et des références d'anciens propriétaires, à condition de le faire pour tous les candidats.",
    question: "Qu'est-ce qui est légal pour le propriétaire ?",
    options: ["Refuser les familles avec enfants", "Exiger une enquête de crédit pour tous", "Demander des références à certains candidats seulement", "Exiger un an de loyer d'avance"],
    answer: 1,
    explanation: "« En revanche » sépare l'interdit du permis ; la condition « pour tous les candidats » élimine l'option discriminatoire.",
  },
  {
    id: "ce-12", topic: "société", level: 2, source: s,
    passage: "La fréquentation des bibliothèques municipales a augmenté de 18 % en trois ans. Les responsables y voient l'effet des nouveaux services : ateliers de conversation française, prêt d'instruments de musique et aide aux devoirs. Le livre n'est plus la seule porte d'entrée.",
    question: "Comment le texte explique-t-il la hausse de fréquentation ?",
    options: ["Par la gratuité des lieux", "Par la diversification des services", "Par la fermeture des librairies", "Par la baisse du prix des livres"],
    answer: 1,
    explanation: "La cause est introduite par « y voient l'effet des nouveaux services », puis illustrée par trois exemples.",
  },
  {
    id: "ce-13", topic: "vie pratique", level: 2, source: s,
    passage: "Votre colis n'a pas pu être livré le 4 avril (absence du destinataire). Il est disponible au point de retrait du 620, avenue Papineau pendant dix jours ouvrables. Passé ce délai, il sera retourné à l'expéditeur. Pièce d'identité obligatoire.",
    question: "Que se passera-t-il si le colis n'est pas récupéré à temps ?",
    options: ["Une nouvelle livraison sera tentée", "Il sera détruit", "Il sera renvoyé à l'expéditeur", "Il restera au point de retrait"],
    answer: 2,
    explanation: "« Passé ce délai » introduit la conséquence exacte. Les trois autres options ne figurent nulle part.",
  },
  {
    id: "ce-14", topic: "travail", level: 3, source: s,
    passage: "L'entreprise n'a pas l'obligation de payer les pauses-café. Elle doit en revanche rémunérer la période de repas lorsque le salarié est tenu de rester à son poste, par exemple un gardien de sécurité qui mange devant ses écrans de surveillance.",
    question: "Quelle est la fonction de l'exemple du gardien ?",
    options: ["Contredire la règle énoncée", "Illustrer le cas où le repas est payé", "Montrer une exception illégale", "Introduire un nouveau sujet"],
    answer: 1,
    explanation: "« par exemple » signale une illustration de la règle qui précède — question de fonction du texte, fréquente à l'examen.",
  },
  {
    id: "ce-15", topic: "santé", level: 2, source: s,
    passage: "La clinique sans rendez-vous ouvre à 8 h, mais la file commence souvent avant 7 h. Autre option : l'inscription en ligne dès 6 h, qui attribue une place dans la file virtuelle et envoie un texto trente minutes avant votre tour.",
    question: "Quel avantage offre l'inscription en ligne ?",
    options: ["Une consultation à domicile", "Éviter l'attente sur place grâce au texto", "Un rendez-vous garanti à 8 h", "Un accès prioritaire aux urgences"],
    answer: 1,
    explanation: "L'avantage se déduit du fonctionnement décrit : file virtuelle + alerte texto = pas d'attente physique.",
  },
  {
    id: "ce-16", topic: "études", level: 3, source: s,
    passage: "Le mentorat étudiant repose sur un principe simple : on retient mieux ce qu'on explique. Les mentors, sélectionnés parmi les étudiants de troisième année, consolident ainsi leurs propres acquis tout en aidant les nouveaux. C'est pourquoi le programme est présenté comme gagnant-gagnant.",
    question: "Pourquoi le programme est-il « gagnant-gagnant » ?",
    options: ["Les mentors sont payés", "Les deux parties progressent", "Les nouveaux obtiennent de meilleures notes garanties", "L'université économise des cours"],
    answer: 1,
    explanation: "« consolident leurs propres acquis tout en aidant » : le bénéfice mutuel est la cause introduite par « C'est pourquoi ».",
  },
  {
    id: "ce-17", topic: "logement", level: 1, source: s,
    passage: "Appartement 3 ½ à louer, rue Fabre. Libre le 1er juillet. 1 150 $/mois, électricité non comprise. Animaux acceptés sauf chiens de plus de 15 kg. Visites samedi de 10 h à 13 h, sans rendez-vous.",
    question: "Quel animal serait refusé dans ce logement ?",
    options: ["Un chat", "Un petit chien", "Un chien de 20 kg", "Un oiseau"],
    answer: 2,
    explanation: "« sauf chiens de plus de 15 kg » : la restriction ne vise qu'une catégorie précise.",
  },
  {
    id: "ce-18", topic: "société", level: 2, source: s,
    passage: "Faut-il craindre la disparition des caissiers ? Les caisses automatiques se multiplient, c'est un fait. Mais les enseignes qui les ont généralisées font marche arrière : vols en hausse, clients âgés découragés, files paradoxalement plus longues. L'humain revient par la porte de service.",
    question: "Que font certaines enseignes aujourd'hui ?",
    options: ["Elles ajoutent des caisses automatiques", "Elles reviennent partiellement aux caissiers", "Elles ferment leurs magasins", "Elles baissent leurs prix"],
    answer: 1,
    explanation: "« font marche arrière » + « l'humain revient » : deux formulations imagées de la même idée — le vocabulaire figuré est un piège courant.",
  },
  {
    id: "ce-19", topic: "vie pratique", level: 1, source: s,
    passage: "Recette express — Faites cuire les pâtes huit minutes. Pendant ce temps, faites revenir l'ail dans l'huile d'olive à feu doux : s'il brunit, il devient amer et il faut recommencer. Mélangez le tout hors du feu avec le basilic.",
    question: "Pourquoi faut-il surveiller l'ail ?",
    options: ["Il cuit en huit minutes", "Bruni, il donne un goût amer", "Il doit être ajouté en dernier", "Il remplace le sel"],
    answer: 1,
    explanation: "La cause est explicite : « s'il brunit, il devient amer ». Question de compréhension causale directe.",
  },
  {
    id: "ce-20", topic: "travail", level: 2, source: s,
    passage: "Objet : Horaire d'été — À compter du 24 juin, les bureaux fermeront à 13 h le vendredi. Les heures non travaillées seront réparties du lundi au jeudi (fin de journée à 17 h 30 au lieu de 17 h). Cette mesure prendra fin la première semaine de septembre.",
    question: "Comment les heures du vendredi après-midi sont-elles compensées ?",
    options: ["Elles sont perdues sans compensation", "Par 30 minutes de plus du lundi au jeudi", "Par du travail le samedi", "Par une réduction de salaire"],
    answer: 1,
    explanation: "« réparties du lundi au jeudi » + le détail des horaires (17 h 30 au lieu de 17 h) donnent le calcul.",
  },
  {
    id: "ce-21", topic: "santé", level: 3, source: s,
    passage: "On attribue souvent la fatigue hivernale au froid. Or, les spécialistes pointent plutôt le manque de lumière : la baisse d'exposition dérègle l'horloge interne et la production de mélatonine. D'où leur conseil : sortir au moins trente minutes en matinée, même par temps gris.",
    question: "Quelle est la cause principale de la fatigue hivernale selon les spécialistes ?",
    options: ["Le froid", "Le manque de lumière", "Le manque de sommeil", "L'alimentation"],
    answer: 1,
    explanation: "« Or » corrige l'idée reçue (le froid) et introduit la vraie cause. Le connecteur porte tout le sens.",
  },
  {
    id: "ce-22", topic: "études", level: 2, source: s,
    passage: "Le test de classement de français est obligatoire pour tous les nouveaux admis, sauf pour les titulaires d'un diplôme d'études secondaires obtenu en français au cours des cinq dernières années. Le résultat détermine le niveau du cours, non l'admission elle-même.",
    question: "À quoi sert le résultat du test ?",
    options: ["À accepter ou refuser l'admission", "À classer l'étudiant dans le bon niveau", "À attribuer une bourse", "À dispenser de cours de français"],
    answer: 1,
    explanation: "« détermine le niveau du cours, non l'admission » — la fin de phrase écarte explicitement l'option 1.",
  },
  {
    id: "ce-23", topic: "logement", level: 2, source: s,
    passage: "Assurance habitation locataire — Votre contrat couvre vos biens (vol, incendie, dégât d'eau) et votre responsabilité civile. Il ne couvre pas le bâtiment lui-même : c'est l'affaire de l'assurance du propriétaire. Franchise : 500 $ par réclamation.",
    question: "Qu'est-ce qui n'est PAS couvert par ce contrat ?",
    options: ["Le vol des biens du locataire", "Un dégât d'eau sur les meubles", "Les dommages au bâtiment", "La responsabilité civile"],
    answer: 2,
    explanation: "Les questions négatives (« n'est PAS ») exigent d'éliminer tout ce qui est listé comme couvert.",
  },
  {
    id: "ce-24", topic: "société", level: 3, source: s,
    passage: "Le bénévolat des retraités est souvent décrit comme un don de temps. La réalité est plus circulaire : les études montrent que les bénévoles réguliers déclarent un meilleur moral et une meilleure santé perçue que les non-bénévoles du même âge. Donner, ici, c'est aussi recevoir.",
    question: "Quelle idée la dernière phrase résume-t-elle ?",
    options: ["Le bénévolat épuise les retraités", "Le bénévolat bénéficie aussi à ceux qui le pratiquent", "Les retraités manquent de temps", "Les études se contredisent"],
    answer: 1,
    explanation: "« Donner, c'est aussi recevoir » condense la phrase précédente : moral et santé perçue meilleurs chez les bénévoles.",
  },
  {
    id: "ce-25", topic: "vie pratique", level: 1, source: s,
    passage: "Programme de la fête de quartier — 10 h : marché fermier. 12 h : pique-nique communautaire (apportez un plat à partager). 14 h : jeux pour enfants. En cas de pluie, l'ensemble des activités est déplacé au gymnase de l'école Saint-Gérard.",
    question: "Que se passe-t-il en cas de pluie ?",
    options: ["La fête est annulée", "Seuls les jeux sont annulés", "Tout est déplacé au gymnase", "La fête est reportée au lendemain"],
    answer: 2,
    explanation: "« l'ensemble des activités est déplacé » — ni annulation ni report : lisez le verbe exact.",
  },
  {
    id: "ce-26", topic: "travail", level: 2, source: s,
    passage: "Votre relevé d'emploi a été transmis par votre ancien employeur. Pour compléter votre demande d'assurance-emploi, vous devez maintenant déclarer vos deux dernières semaines de travail en ligne, puis répondre aux déclarations toutes les deux semaines, même si votre situation ne change pas.",
    question: "À quelle fréquence faut-il remplir les déclarations ?",
    options: ["Une seule fois", "Chaque semaine", "Toutes les deux semaines", "Seulement si la situation change"],
    answer: 2,
    explanation: "« même si votre situation ne change pas » élimine le piège de l'option 4, qui reprend des mots du texte.",
  },
  {
    id: "ce-27", topic: "santé", level: 1, source: s,
    passage: "Ligne info-santé — Composez le 811 pour parler à une infirmière, 24 heures sur 24. Ce service ne remplace pas les urgences : en cas de douleur thoracique, de difficulté respiratoire ou de perte de conscience, composez immédiatement le 911.",
    question: "Dans quel cas faut-il appeler le 911 plutôt que le 811 ?",
    options: ["Pour une question sur un médicament", "Pour une douleur thoracique", "Pour un conseil de prévention", "Pour prendre rendez-vous"],
    answer: 1,
    explanation: "Le texte oppose deux numéros et liste les urgences vitales : la douleur thoracique en fait partie.",
  },
  {
    id: "ce-28", topic: "études", level: 2, source: s,
    passage: "Chère étudiante, cher étudiant, — Votre demande de bourse a été jugée admissible. Attention : admissible ne signifie pas accordée. Le comité classera tous les dossiers admissibles en juin, en fonction des résultats scolaires et de la situation financière. Réponse définitive : mi-juillet.",
    question: "Que signifie « admissible » dans cette lettre ?",
    options: ["La bourse est accordée", "Le dossier peut concourir, sans garantie", "Le dossier est refusé", "Il manque des documents"],
    answer: 1,
    explanation: "La lettre définit elle-même le mot : « admissible ne signifie pas accordée ». L'examen adore ces nuances lexicales.",
  },
  {
    id: "ce-29", topic: "logement", level: 3, source: s,
    passage: "Un logement est dit « chauffé » lorsque le coût du chauffage est inclus dans le loyer ; il est « éclairé » lorsque l'électricité l'est aussi. Un 4 ½ « chauffé, non éclairé » à 1 200 $ peut donc revenir plus cher qu'un 4 ½ « chauffé, éclairé » à 1 260 $, selon votre consommation.",
    question: "Pourquoi le logement à 1 200 $ peut-il coûter plus cher au total ?",
    options: ["Son loyer augmente chaque année", "Il faut y ajouter l'électricité", "Il est plus grand", "Le chauffage y est en supplément"],
    answer: 1,
    explanation: "« non éclairé » = électricité à votre charge. Le calcul implicite (1 200 + électricité vs 1 260 tout compris) est le cœur de la question.",
  },
  {
    id: "ce-30", topic: "société", level: 2, source: s,
    passage: "Les applications de covoiturage domicile-travail peinent à décoller en région. La raison principale n'est pas le prix, jugé attractif, mais l'irrégularité des horaires : quarts de soir, heures supplémentaires imprévues, gardes. Difficile de partager un trajet quand on ne sait pas à quelle heure on termine.",
    question: "Qu'est-ce qui freine le covoiturage en région ?",
    options: ["Le prix trop élevé", "Le manque d'applications", "L'imprévisibilité des horaires de travail", "L'état des routes"],
    answer: 2,
    explanation: "« La raison principale n'est pas le prix… mais » : structure de correction typique, la réponse suit le « mais ».",
  },
  {
    id: "ce-31", topic: "vie pratique", level: 2, source: s,
    passage: "Banque — Alerte de sécurité. Nous ne vous demanderons JAMAIS votre mot de passe ni votre code par courriel ou par texto. Si vous recevez un tel message, ne cliquez sur aucun lien et transférez-le à fraude@banque.ca avant de le supprimer.",
    question: "Que faire si l'on reçoit un courriel demandant son mot de passe ?",
    options: ["Répondre avec le mot de passe", "Cliquer sur le lien pour vérifier", "Le transférer au service antifraude puis le supprimer", "Changer de banque"],
    answer: 2,
    explanation: "Deux consignes enchaînées : transférer, puis supprimer. L'ordre des actions compte dans les textes de consignes.",
  },
  {
    id: "ce-32", topic: "travail", level: 3, source: s,
    passage: "Le « présentéisme » — venir travailler malade — coûterait aux entreprises plus cher que l'absentéisme : contagion des collègues, erreurs accrues, récupération plus lente. Certaines entreprises l'ont compris, qui envoient désormais fermement leurs salariés fiévreux se reposer chez eux.",
    question: "Pourquoi le présentéisme coûte-t-il cher ?",
    options: ["Les salariés absents sont mal remplacés", "Il combine contagion, erreurs et guérison retardée", "Les salaires des malades sont doublés", "Les bureaux restent vides"],
    answer: 1,
    explanation: "Les trois coûts sont énumérés après les deux-points — le mot inventé « présentéisme » est défini par le tiret.",
  },
  {
    id: "ce-33", topic: "santé", level: 2, source: s,
    passage: "La carte d'assurance maladie doit être renouvelée avant sa date d'expiration. Le renouvellement en ligne est réservé aux personnes dont la photo a moins de dix ans ; les autres doivent se présenter en personne avec deux pièces d'identité.",
    question: "Qui doit se déplacer pour renouveler sa carte ?",
    options: ["Tout le monde", "Les personnes dont la photo date de plus de dix ans", "Les nouveaux arrivants seulement", "Personne, tout se fait en ligne"],
    answer: 1,
    explanation: "La restriction « réservé aux… » définit en creux qui est exclu du service en ligne.",
  },
  {
    id: "ce-34", topic: "études", level: 3, source: s,
    passage: "Prendre des notes à la main serait plus efficace qu'à l'ordinateur, non pas malgré sa lenteur, mais grâce à elle : forcé de reformuler au lieu de tout transcrire, l'étudiant traite l'information en profondeur dès la prise de notes.",
    question: "Pourquoi la lenteur de l'écriture manuelle est-elle un avantage ?",
    options: ["Elle repose les yeux", "Elle oblige à reformuler, donc à comprendre", "Elle évite les fautes de frappe", "Elle permet de tout noter mot à mot"],
    answer: 1,
    explanation: "« non pas malgré sa lenteur, mais grâce à elle » : le renversement logique est la clé — l'option 4 dit l'inverse du texte.",
  },
  {
    id: "ce-35", topic: "logement", level: 2, source: s,
    passage: "État des lieux d'entrée — Notez tout défaut existant (rayures, taches, fissures) et photographiez-les, datées. Ce document, signé par les deux parties, vous protégera au départ : sans lui, le propriétaire pourrait vous facturer des dommages antérieurs à votre arrivée.",
    question: "À quoi sert l'état des lieux d'entrée ?",
    options: ["À fixer le montant du loyer", "À prouver l'état initial et éviter des frais injustes", "À réserver le logement", "À obtenir une assurance"],
    answer: 1,
    explanation: "La finalité est dans « vous protégera au départ » ; la conséquence sans document explicite le risque évité.",
  },
  {
    id: "ce-36", topic: "société", level: 2, source: s,
    passage: "Les jardins communautaires affichent complet partout : trois ans d'attente en moyenne pour obtenir une parcelle. Les villes tentent d'y répondre par des « jardinets de trottoir », ces bacs plantés devant les immeubles, entretenus librement par les riverains volontaires.",
    question: "Que sont les « jardinets de trottoir » ?",
    options: ["Des parcelles des jardins communautaires", "Des bacs de plantation devant les immeubles", "Des marchés de fruits et légumes", "Des parcs municipaux"],
    answer: 1,
    explanation: "La définition suit immédiatement le terme entre guillemets, après « ces » — réflexe à acquérir pour le vocabulaire inconnu.",
  },
  {
    id: "ce-37", topic: "vie pratique", level: 1, source: s,
    passage: "Garderie Les Petits Pas — Rappel aux parents : les enfants malades (fièvre, vomissements) ne peuvent pas être accueillis. Si votre enfant présente des symptômes pendant la journée, vous serez appelé et devrez venir le chercher dans l'heure.",
    question: "Que doit faire un parent appelé par la garderie ?",
    options: ["Envoyer un médicament", "Venir chercher l'enfant dans l'heure", "Rappeler le lendemain", "Envoyer un autre membre de la famille la semaine suivante"],
    answer: 1,
    explanation: "L'obligation est formulée avec « devrez » + délai précis « dans l'heure » : question de repérage direct.",
  },
  {
    id: "ce-38", topic: "travail", level: 2, source: s,
    passage: "Entretien d'embauche à distance : trois erreurs reviennent sans cesse. Un arrière-plan désordonné, d'abord, qui distrait l'évaluateur. Un regard fixé sur l'écran plutôt que sur la caméra, ensuite, qui casse le contact. Enfin, l'absence de questions en fin d'entretien, perçue comme un manque d'intérêt.",
    question: "Pourquoi faut-il regarder la caméra et non l'écran ?",
    options: ["Pour mieux lire les questions", "Pour maintenir le contact visuel avec l'évaluateur", "Pour vérifier sa propre image", "Pour éviter la fatigue oculaire"],
    answer: 1,
    explanation: "« qui casse le contact » : chaque erreur est suivie de sa conséquence. Les connecteurs (d'abord, ensuite, enfin) structurent la liste.",
  },
  {
    id: "ce-39", topic: "études", level: 1, source: s,
    passage: "Cours de francisation — Session d'automne. Inscription en ligne du 1er au 15 août. Places limitées, priorité aux personnes inscrites à temps plein. Une liste d'attente sera ouverte dès que les groupes seront complets.",
    question: "Qui est prioritaire pour l'inscription ?",
    options: ["Les premiers arrivés", "Les personnes à temps plein", "Les résidents du quartier", "Les personnes sur liste d'attente"],
    answer: 1,
    explanation: "« priorité aux personnes inscrites à temps plein » — la liste d'attente concerne un autre moment du processus.",
  },
  {
    id: "ce-40", topic: "société", level: 3, source: s,
    passage: "Interdire les écrans aux enfants ? La formule fait recette, mais elle simplifie le débat. Les chercheurs distinguent les usages : une visioconférence avec les grands-parents ne « vaut » pas une heure de vidéos automatiques. Le temps d'écran est un thermomètre commode ; il ne dit rien de la fièvre.",
    question: "Que signifie la métaphore finale du thermomètre ?",
    options: ["Les écrans rendent les enfants malades", "Mesurer le temps ne suffit pas à juger l'usage", "Il faut interdire les écrans en cas de fièvre", "Les chercheurs manquent d'outils de mesure"],
    answer: 1,
    explanation: "Le thermomètre (la mesure du temps) ne décrit pas la maladie (la qualité de l'usage) : la métaphore condense la distinction faite avant.",
  },
];
