/**
 * SRS bank — 120 original practice cards (source: original practice).
 * Four families: connectors, exam verbs/structures, sound & grammar
 * traps, exam templates (paragraph skeletons).
 */
export interface SrsCard {
  id: string;
  type: "connector" | "verb" | "trap" | "template";
  front: string;
  back: string;
  source: "original practice";
}

const s = "original practice" as const;
const c = (id: string, type: SrsCard["type"], front: string, back: string): SrsCard => ({ id, type, front, back, source: s });

export const SRS_CARDS: SrsCard[] = [
  // ── Connecteurs (40) ──
  c("sr-001", "connector", "Exprimer une opposition forte (2 connecteurs)", "cependant · en revanche — « Le projet est utile ; cependant, son coût est excessif. »"),
  c("sr-002", "connector", "Exprimer une conséquence (registre soutenu)", "par conséquent — « Le réseau est saturé ; par conséquent, il faut investir. »"),
  c("sr-003", "connector", "« néanmoins » : sens et exemple", "= malgré cela. « L'idée séduit ; néanmoins, elle reste coûteuse. »"),
  c("sr-004", "connector", "Structurer 3 arguments à l'oral", "d'abord… ensuite… enfin… — les trois que l'examinateur attend."),
  c("sr-005", "connector", "Ajouter un argument (2 façons)", "de plus · par ailleurs — « De plus, les loyers augmentent. »"),
  c("sr-006", "connector", "Illustrer par un exemple (2 façons)", "par exemple · notamment — « Certains services, notamment la garderie… »"),
  c("sr-007", "connector", "Reformuler une idée", "c'est-à-dire · autrement dit — « Un 4 ½ éclairé, c'est-à-dire électricité incluse. »"),
  c("sr-008", "connector", "Conclure un texte argumenté (3 façons)", "en conclusion · en somme · pour toutes ces raisons"),
  c("sr-009", "connector", "Exprimer la cause : « puisque » vs « parce que »", "puisque = cause connue de tous ; parce que = information nouvelle."),
  c("sr-010", "connector", "« grâce à » vs « à cause de »", "grâce à + résultat positif ; à cause de + résultat négatif."),
  c("sr-011", "connector", "Opposer deux réalités simultanées", "tandis que · alors que — « La ville s'étend, tandis que les services stagnent. »"),
  c("sr-012", "connector", "Concéder avant de réfuter", "certes…, mais… — « Certes, le prix est élevé, mais l'usage le justifie. »"),
  c("sr-013", "connector", "« bien que » se construit avec…", "le SUBJONCTIF : « Bien que le projet soit utile… »"),
  c("sr-014", "connector", "« malgré » se construit avec…", "un NOM : « malgré la pluie » (jamais « malgré que »)."),
  c("sr-015", "connector", "Présenter deux aspects d'un sujet", "d'une part…, d'autre part… — parfait pour le plan en deux arguments."),
  c("sr-016", "connector", "« pourtant » : nuance", "Contraste surprenant : « Il pleut ; pourtant, la fête a lieu. »"),
  c("sr-017", "connector", "« en effet » : usage", "Confirme et justifie ce qui précède : « Le projet avance. En effet, deux tours sont déjà construites. »"),
  c("sr-018", "connector", "« donc » vs « ainsi »", "donc = conséquence logique ; ainsi = conséquence + manière (plus soutenu)."),
  c("sr-019", "connector", "Exprimer le but (2 façons)", "pour + infinitif · afin que + subjonctif."),
  c("sr-020", "connector", "« or » : rôle dans un raisonnement", "Introduit le fait qui fait basculer : « On accuse le froid. Or, la cause est le manque de lumière. »"),
  c("sr-021", "connector", "Marquer une chronologie au passé", "d'abord · puis · ensuite · finalement — indispensables au récit TEF A."),
  c("sr-022", "connector", "« du coup » : registre", "Oral familier seulement. À l'écrit d'examen → « par conséquent », « de ce fait »."),
  c("sr-023", "connector", "« quant à » : sens et piège", "= en ce qui concerne. « Quant au budget… » (ne pas confondre avec « quand »)."),
  c("sr-024", "connector", "Exprimer une condition (3 niveaux)", "si + présent → futur ; si + imparfait → conditionnel ; à condition que + subjonctif."),
  c("sr-025", "connector", "« dès que » vs « depuis que »", "dès que = à partir du moment précis ; depuis que = origine d'une durée."),
  c("sr-026", "connector", "Nuancer une affirmation", "dans une certaine mesure · en partie · plutôt."),
  c("sr-027", "connector", "« en fait » vs « au fait »", "en fait = en réalité ; au fait = au passage, à propos."),
  c("sr-028", "connector", "Résumer avant de conclure", "en résumé · en bref — « En résumé, trois mesures s'imposent. »"),
  c("sr-029", "connector", "Introduire une opinion (4 façons)", "à mon avis · selon moi · d'après moi · pour ma part."),
  c("sr-030", "connector", "Introduire l'opinion adverse avec respect", "certains estiment que · on objectera que · les opposants répondent que."),
  c("sr-031", "connector", "« toutefois » : place dans la phrase", "En tête ou après le verbe : « Le plan est bon ; toutefois, il coûte cher. »"),
  c("sr-032", "connector", "Exprimer une alternative", "soit…, soit… — « Soit une livraison sous 48 h, soit un remboursement. »"),
  c("sr-033", "connector", "« au contraire » vs « par contre »", "au contraire = opposition totale ; par contre = simple contraste (accepté à l'oral)."),
  c("sr-034", "connector", "Enchaîner cause → conséquence en une phrase", "si bien que · de sorte que : « Le bus était plein, si bien que j'ai marché. »"),
  c("sr-035", "connector", "« d'ailleurs » : rôle", "Argument supplémentaire qui renforce : « Ce quartier est vivant ; d'ailleurs, trois cafés viennent d'ouvrir. »"),
  c("sr-036", "connector", "Introduire une restriction", "sauf · à l'exception de · hormis — « Animaux acceptés, sauf chiens de plus de 15 kg. »"),
  c("sr-037", "connector", "« même si » se construit avec…", "l'INDICATIF : « Même si le prix est élevé… » (jamais le subjonctif)."),
  c("sr-038", "connector", "Situer dans le temps un récit", "la veille · le lendemain · une semaine plus tard (et non « hier/demain » dans un récit au passé)."),
  c("sr-039", "connector", "« en ce qui concerne » : usage", "Annonce le thème : « En ce qui concerne le logement, deux options existent. »"),
  c("sr-040", "connector", "Clore poliment une lettre formelle", "« Je vous prie d'agréer, Madame, Monsieur, mes salutations distinguées. »"),

  // ── Verbes et structures d'examen (35) ──
  c("sr-041", "verb", "« il faut que » se construit avec…", "le SUBJONCTIF : « Il faut que vous fassiez une demande écrite. »"),
  c("sr-042", "verb", "Subjonctif de « faire » (que je…)", "que je fasse, que tu fasses, qu'il fasse, que nous fassions, que vous fassiez, qu'ils fassent."),
  c("sr-043", "verb", "Subjonctif de « être » et « avoir »", "que je sois, que tu sois, qu'il soit… / que j'aie, que tu aies, qu'il ait…"),
  c("sr-044", "verb", "Subjonctif de « aller » et « pouvoir »", "que j'aille, que nous allions / que je puisse, que vous puissiez."),
  c("sr-045", "verb", "Passé composé ou imparfait : la règle en une ligne", "PC = action ponctuelle qui fait avancer l'histoire ; imparfait = décor, habitude, description."),
  c("sr-046", "verb", "« Quand je suis sorti, il ___ (pleuvoir) »", "il pleuvait — décor à l'imparfait autour d'une action au passé composé."),
  c("sr-047", "verb", "Accord du participe avec « être »", "Avec être, accord avec le sujet : « Elle est arrivée » ; « Ils sont partis »."),
  c("sr-048", "verb", "Accord du participe avec « avoir »", "Accord avec le COD placé AVANT : « La lettre que j'ai écrite ». Sinon invariable."),
  c("sr-049", "verb", "Le pronom « y » remplace…", "un lieu ou « à + chose » : « J'y vais » ; « J'y pense »."),
  c("sr-050", "verb", "Le pronom « en » remplace…", "« de + chose » ou une quantité : « J'en ai deux » ; « J'en parle »."),
  c("sr-051", "verb", "« J'ai besoin de ce document » → pronom", "« J'en ai besoin. » (besoin DE → en)"),
  c("sr-052", "verb", "« Je vais à la banque » → pronom", "« J'y vais. » (lieu → y)"),
  c("sr-053", "verb", "Ordre des doubles pronoms", "me/te/nous/vous + le/la/les + lui/leur + y + en : « Je le lui donne » ; « Il m'en a parlé »."),
  c("sr-054", "verb", "Négation complète d'un verbe composé", "ne + auxiliaire + pas + participe : « Je n'ai pas reçu le colis. »"),
  c("sr-055", "verb", "« ne… que » signifie…", "seulement : « Il ne reste que deux places. » (ce n'est PAS une négation)"),
  c("sr-056", "verb", "Question formelle avec inversion", "« Pourriez-vous m'indiquer les horaires ? » — la forme attendue à l'écrit formel."),
  c("sr-057", "verb", "Trois façons de poser une question", "intonation (oral) · est-ce que (neutre) · inversion (formel)."),
  c("sr-058", "verb", "Conditionnel de politesse (3 verbes clés)", "je voudrais · je souhaiterais · vous serait-il possible de…"),
  c("sr-059", "verb", "« Si j'avais le temps, je ___ (faire) du sport »", "je ferais — si + imparfait → conditionnel présent."),
  c("sr-060", "verb", "Futur proche vs futur simple", "aller + inf. = décision/proche (« je vais appeler ») ; futur simple = projet/promesse (« je vous répondrai »)."),
  c("sr-061", "verb", "« depuis » + présent : piège des anglophones", "« J'habite ici depuis deux ans » (présent, PAS « j'ai habité »)."),
  c("sr-062", "verb", "« venir de » + infinitif", "passé immédiat : « Je viens de recevoir votre courriel. »"),
  c("sr-063", "verb", "« être en train de » + infinitif", "action en cours : « Je suis en train de rédiger la lettre. »"),
  c("sr-064", "verb", "Verbes + à : les 5 fréquents à l'examen", "réussir à · penser à · s'inscrire à · répondre à · participer à."),
  c("sr-065", "verb", "Verbes + de : les 5 fréquents à l'examen", "décider de · essayer de · avoir besoin de · s'occuper de · remercier de."),
  c("sr-066", "verb", "« demander à qqn de faire »", "« Je demande au propriétaire de réparer le chauffage. » (à + personne, de + inf.)"),
  c("sr-067", "verb", "Impératif poli à l'écrit", "« Veuillez trouver ci-joint… » ; « Merci de me confirmer… »"),
  c("sr-068", "verb", "« s'agir de » : usage soutenu", "« Il s'agit d'un problème urgent. » — toujours impersonnel (il)."),
  c("sr-069", "verb", "Voix passive utile à l'écrit", "« La décision a été prise » ; « Les images seront effacées sous sept jours »."),
  c("sr-070", "verb", "Discours rapporté au passé : « il a dit que… »", "présent → imparfait : « Il a dit qu'il était disponible. »"),
  c("sr-071", "verb", "« avant de » vs « après avoir »", "avant de + infinitif présent ; après avoir/être + participe : « après avoir vérifié »."),
  c("sr-072", "verb", "Exprimer la durée : pendant / pour / en", "pendant = durée vécue ; pour = durée prévue ; en = temps nécessaire (« en dix minutes »)."),
  c("sr-073", "verb", "Gérondif : forme et usage", "en + -ant : « En arrivant, appelez-moi. » — deux actions, même sujet."),
  c("sr-074", "verb", "« faire faire » (faire causatif)", "« Je fais réparer le chauffage » = quelqu'un d'autre répare."),
  c("sr-075", "verb", "« il vaut mieux » + infinitif / que + subj.", "« Il vaut mieux réserver » ; « Il vaut mieux que vous réserviez »."),

  // ── Pièges de sons et de grammaire (25) ──
  c("sr-076", "trap", "PIÈGE SON : « plus » [plys] vs [ply]", "« J'en veux plus [plys] » = davantage ; « Je n'en veux plus [ply] » = arrêt. En CO, le [s] change tout."),
  c("sr-077", "trap", "PIÈGE SON : « des » vs « de » après négation", "« J'ai des questions » → « Je n'ai pas de questions ». La négation transforme des → de."),
  c("sr-078", "trap", "PIÈGE SON : deux / douze — dictée de nombres", "deux [dø] · douze [duz]. Les annonces d'horaires jouent sur cette paire."),
  c("sr-079", "trap", "PIÈGE SON : dessus / dessous", "dessUS [dəsy] = en haut ; dessOUS [dəsu] = en bas."),
  c("sr-080", "trap", "PIÈGE : quinze heures dix ≠ quinze heures moins dix", "15 h 10 vs 14 h 50 — « moins » inverse. Notez les heures en chiffres pendant l'écoute."),
  c("sr-081", "trap", "PIÈGE : soixante-dix / soixante-seize", "70 vs 76 — et quatre-vingt-dix (90) vs quatre-vingt-seize (96). Dictée mentale obligatoire."),
  c("sr-082", "trap", "PIÈGE genre : les 6 masculins qu'on croit féminins", "un problème · un système · un programme · un modèle · un groupe · un domaine."),
  c("sr-083", "trap", "PIÈGE genre : les 6 féminins qu'on croit masculins", "une équipe · une entreprise · une erreur · une eau · une annonce · une attitude."),
  c("sr-084", "trap", "PIÈGE : « la plupart des gens » + verbe…", "au PLURIEL : « La plupart des gens prennent le bus. »"),
  c("sr-085", "trap", "PIÈGE : an / année, jour / journée", "an, jour = unité de compte (« deux ans ») ; année, journée = durée vécue (« toute la journée »)."),
  c("sr-086", "trap", "PIÈGE : « visiter » une personne ?", "Non. On visite un LIEU ; on rend visite À une personne."),
  c("sr-087", "trap", "PIÈGE : « actuellement » ≠ actually", "actuellement = en ce moment. « en fait » = actually. Faux ami classique."),
  c("sr-088", "trap", "PIÈGE : « éventuellement » ≠ eventually", "éventuellement = peut-être. « finalement » = eventually."),
  c("sr-089", "trap", "PIÈGE : « rester » ≠ to rest", "rester = ne pas partir. Se reposer = to rest. « Je suis resté chez moi pour me reposer. »"),
  c("sr-090", "trap", "PIÈGE : attendre / s'attendre à", "attendre = wait ; s'attendre à = expect. « Je m'attendais à une réponse rapide. »"),
  c("sr-091", "trap", "PIÈGE : « bon » vs « bien »", "bon = adjectif (un bon plan) ; bien = adverbe (il travaille bien). « C'est bon » ≠ « c'est bien »."),
  c("sr-092", "trap", "PIÈGE : « amener » vs « apporter »", "apporter = objet (« apportez une boisson ») ; amener = personne (« j'amène ma sœur »)."),
  c("sr-093", "trap", "PIÈGE : « savoir » vs « connaître »", "savoir + fait/faire (« je sais conduire ») ; connaître + nom (« je connais ce quartier »)."),
  c("sr-094", "trap", "PIÈGE : « entendre » vs « écouter »", "entendre = percevoir ; écouter = volontaire. En CO : « il a entendu » ≠ « il écoutait »."),
  c("sr-095", "trap", "PIÈGE écrit : « a » vs « à »", "a = verbe avoir (« il a froid ») ; à = préposition (« à Montréal »). Erreur éliminatoire à l'écrit."),
  c("sr-096", "trap", "PIÈGE écrit : « ce » vs « se »", "ce + nom (« ce projet ») ; se + verbe (« il se lève »)."),
  c("sr-097", "trap", "PIÈGE écrit : « leur » vs « leurs »", "leur + verbe = invariable (« je leur parle ») ; leur/leurs + nom s'accorde (« leurs enfants »)."),
  c("sr-098", "trap", "PIÈGE : « c'est » vs « il est » + profession", "« Il est médecin » (sans article) ; « C'est un médecin réputé » (avec article)."),
  c("sr-099", "trap", "PIÈGE : « mieux » vs « meilleur »", "meilleur = adjectif (une meilleure solution) ; mieux = adverbe (ça va mieux)."),
  c("sr-100", "trap", "PIÈGE CO : l'option qui répète un mot du texte…", "…est souvent FAUSSE. L'examen paraphrase la bonne réponse et recycle les mots exacts dans les pièges."),

  // ── Gabarits d'examen (20) ──
  c("sr-101", "template", "Squelette du paragraphe d'opinion (4 temps)", "1. Opinion (« À mon avis… ») 2. Raison (« car… ») 3. Exemple (« Par exemple… ») 4. Bilan (« C'est pourquoi… »)."),
  c("sr-102", "template", "Ouverture d'une lettre formelle (destinataire inconnu)", "« Madame, Monsieur, » — jamais « Cher Madame » ni « Bonjour » seul dans une lettre formelle."),
  c("sr-103", "template", "Premier paragraphe d'une réclamation", "Fait + référence : « Je me permets de vous contacter au sujet de la commande n° …, passée le … »"),
  c("sr-104", "template", "Exiger poliment (réclamation)", "« Je vous demande donc soit …, soit … » + délai : « sous 48 heures »."),
  c("sr-105", "template", "Structure TEF B en 5 blocs", "Position → Argument 1 + exemple → Argument 2 + exemple → Concession (« Certes… mais ») → Demande/conclusion."),
  c("sr-106", "template", "La concession qui rapporte des points", "« Certes, [argument adverse honnête], mais [votre réfutation précise]. »"),
  c("sr-107", "template", "Proposer une alternative (lettre au maire, etc.)", "« C'est pourquoi je propose … » + solution concrète + bénéfice chiffré si possible."),
  c("sr-108", "template", "Invitation amicale : les 4 informations", "Quoi + quand + où/comment venir + quoi apporter — et demander confirmation."),
  c("sr-109", "template", "S'excuser et reporter (courriel)", "« Je suis au regret de devoir reporter… » + raison courte + « Vous serait-il possible de… » + 2 créneaux."),
  c("sr-110", "template", "Demande de renseignements : plan en 3 questions", "Horaires/dates → prix/conditions → modalités d'inscription. Finir par : « Je vous remercie par avance. »"),
  c("sr-111", "template", "Début d'un récit au passé (TEF A)", "Décor à l'imparfait (« Il pleuvait, j'attendais… ») puis bascule au passé composé (« quand soudain, on a annoncé… »)."),
  c("sr-112", "template", "EO : se lancer sans paniquer (3 amorces)", "« Alors, pour commencer… » · « En fait, ce que je veux dire, c'est que… » · « Disons que… »"),
  c("sr-113", "template", "EO TEF A : la salutation téléphonique complète", "« Bonjour, je vous appelle au sujet de votre annonce pour… J'aurais quelques questions. »"),
  c("sr-114", "template", "EO TEF A : varier ses questions (6 formes)", "Quel(le)… ? Combien… ? Où… ? Quand… ? Est-ce que… ? Comment… ? — jamais six fois « est-ce que »."),
  c("sr-115", "template", "EO TEF B : traiter une objection", "« Je comprends que [objection]. Cela dit, [réponse] + [garantie concrète]. »"),
  c("sr-116", "template", "EO : conclure proprement", "« Voilà pourquoi je pense que… En un mot : [idée clé]. » — ne jamais finir sur un silence."),
  c("sr-117", "template", "Avantages/inconvénients (TCF T3)", "« D'un côté… De l'autre… Tout bien pesé, je penche pour… car… »"),
  c("sr-118", "template", "Décrire une expérience (TCF T2) en 4 temps", "Contexte (imparfait) → événement (PC) → résultat → leçon (« Cette expérience m'a appris que… »)."),
  c("sr-119", "template", "Clôture d'un courriel professionnel (3 registres)", "Soutenu : « Je vous prie d'agréer… » · Standard : « Cordialement » · Suivi attendu : « Dans l'attente de votre réponse »."),
  c("sr-120", "template", "Gagner 5 secondes de réflexion en EO", "« C'est une excellente question… » · « Voyons… » · « Comment dire… » — remplisseurs français, jamais de silence anglais."),
];
